# launch_function works even on exception

    Code
      result$error
    Output
      [1] "argument \"sec\" is missing, with no default"

